import type { Metadata } from 'next';
import './globals.css';
import 'swiper/css';
import 'swiper/css/effect-fade';
import Providers from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white relative flex flex-col">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
