import type { Metadata } from 'next';
import './globals.css';
import 'swiper/css';
import 'swiper/css/effect-fade';
import Header from '@/components/header';
import Footer from '@/components/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-netflix bg-black text-white relative">
        <Header />
        <div className="pb-12">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
